apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-idea-c
  labels:
    helm.sh/chart: idea-c-1.0.20240222-beta
    app.kubernetes.io/name: idea-c
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    userName: zhangsan
    userId: "123"
    userRole: developer
    ideType: idea-c
  namespace: demo
data:
  .git-credentials: |-
      http://zhangsan:123456@192.168.184.25
      https://zhangsan:123456@gitee.com
      https://zhangsan:123456@code.srdcloud.cn
  .gitconfig: |-
      [credential "http://192.168.184.25"]
          provider = generic
      [credential "https://gitee.com"]
          provider = generic
      [credential "https://code.srdcloud.cn"]
          provider = generic
      [user]
          name = zhangsan
          email = 2694484453@qq.com
      [core]
          longpaths = true
      [http]
          sslVerify = false
          postBuffer = 5.24288e+08
      [credential]
          helper = 'store'
