apiVersion: v1
kind: Service
metadata:
  name: gpu-metrics-svc
  namespace: monitoring
  labels:
    app.kubernetes.io/name: aggregated-trace-metrics
spec:
  clusterIP: None
  ports:
    - name: aggregated-trace-metrics
      port: 8889
      protocol: TCP
      targetPort: 8889
---

