apiVersion: v1
kind: Service
metadata:
  name: cloud-server
  namespace: monitoring
  labels:
    app.kubernetes.io/name: cloud-server
spec:
  type: ExternalName
  externalName: my-server.gpg123.vip
  ports:
    - port: 9099
      name: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-server-monitor
  namespace: monitoring
  labels:
    app.kubernetes.io/name: cloud-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloud-server
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - monitoring
#ping cloud-server.monitoring.svc.cluster.local
#wget
