apiVersion: v1
kind: Endpoints
metadata:
  name: es-exporter
  namespace: monitoring
subsets:
  - addresses:
      - ip: 110.42.40.8
    ports:
      - port: 9108
        protocol: TCP
        name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: es-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: es-exporter
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: es-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s