apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      name: metrics
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jaeger
  namespace: monitoring
subsets:
  - addresses:
      - ip: 124.221.2.29
    ports:
      - port: 8888
        protocol: TCP
        name: metrics

