apiVersion: v1
kind: Endpoints
metadata:
  name: metrics-endpoints
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus-metrics-endpoints
subsets:
  - addresses:
      - ip: 124.221.2.29
    ports:
      - name: aggregated-trace-metrics
        port: 8889
        protocol: TCP
      - name: jaeger
        port: 188
        protocol: TCP
      - name: cloud-server
        port: 9099
        protocol: TCP
  - addresses:
      - ip: 47.97.162.27
    ports:
      - name: traefik
        port: 9100
        protocol: TCP
