apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-demo-monitor
  namespace: monitoring
  labels:
    app.kubernetes.io/name: spring-boot-demo
spec:
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-boot-demo
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
