apiVersion: v1
kind: Service
metadata:
  name: traefik-ecs
  namespace: monitoring
  labels:
    kubernetes.io/service-name: traefik-ecs
spec:
  selector:
    app.kubernetes.io/name: traefik-ecs
  ports:
    - port: 9100
      protocol: TCP
      name: traefik
---
apiVersion: v1
kind: Endpoints
metadata:
  name: traefik-ecs
  namespace: monitoring
  labels:
    app.kubernetes.io/name: traefik-ecs
subsets:
  - addresses:
      - ip: 47.97.162.27
    ports:
      - port: 9100
        protocol: TCP
        name: traefik
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-ecs-monitor
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus-metrics
spec:
  selector:
    matchLabels:
      kubernetes.io/service-name: traefik-ecs
  endpoints:
    - port: traefik
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - monitoring
