apiVersion: v1
kind: Service
metadata:
  name: traefik-ecs
  namespace: monitoring
  labels:
    kubernetes.io/service-name: traefik-ecs
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - port: 9100
      protocol: TCP
      name: traefik
---
apiVersion: v1
kind: Endpoints
metadata:
  name: traefik-ecs
  namespace: monitoring
  labels:
    app.kubernetes.io/name: traefik-ecs
subsets:
  - addresses:
      - ip: 47.97.162.27
    ports:
      - port: 9100
        protocol: TCP
        name: traefik
