apiVersion: batch/v1
kind: Job
metadata:
  name: cloud-server-build
  labels:
    maven: "3.6.3"
spec:
  template:
      metadata:
        name: Title
      spec:
        containers:
          - name: Title
            image: busybox:latest
            imagePullPolicy: IfNotPresent
            command:
              - /bin/sh
              - -c
              - date; echo Hello!
        restartPolicy: Never