apiVersion: v1
kind: Service
metadata:
  name: metrics-server-exporter-service
  namespace: kube-system
  labels:
    k8s-app: metrics-server
spec:
  selector:
    k8s-app: metrics-server
  ports:
    - protocol: TCP
      port: 10250
      targetPort: 10250
      name: metrics
      nodePort: 10250
  type: NodePort
