{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ template "spring-boot-demo.fullname" . }}
  labels:
    {{- include "spring-boot-demo.labels" . | nindent 4 }}
    job: serviceMonitor/{{.Release.Namespace}}/{{.Release.Name}}/0
spec:
  route:
    groupBy:
      - job
      - instance
    {{- with .Values.prometheus.alert }}
    groupWait: {{.groupWait}}
    groupInterval: {{.groupInterval}}
    repeatInterval: {{.repeatInterval}}
    receivers:
      {{- if .receivers.webhook }}
      - name: 'webhook'
        webhookConfigs:
        {{- range $k,$v := .receivers.webhook }}
          - url: {{$v}}
            sendNotification: true
         {{- end }}
      {{- end }}
      {{- if .receivers.email }}
      - name: 'email'
        emailConfigs:
        {{- range $k,$v := .receivers.email }}
          - to: {{$v}}
        {{- end }}
      {{- end }}
      {{- end }}
{{- end }}
