apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
  namespace: default
  labels:
    micrometer-prometheus-discovery: 'true'
spec:
  selector:
    app: {{.Release.Name}}
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      name: metrics
