apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "spring-boot-demo.fullname" . }}
  labels:
    {{- include "spring-boot-demo.labels" . | nindent 4 }}
spec:
  gateways:
    - istio-system/biyi-gateway
    - mesh
  hosts:
    - {{ .Release.Name }}.ctbiyi.com
  http:
    - match:
        - headers:
            cookie:
              regex: ^(.*?; ?)?(version=pre)(;.*)?$
      route:
        - destination:
            host: {{ .Release.Name }}
            subset: pre
    - match:
        - sourceLabels:
            version: pre
      route:
        - destination:
            host: {{ .Release.Name }}
            subset: pre
    - route:
        - destination:
            host: {{ .Release.Name }}
            subset: product


