
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  gateways:
    - biyi-gateway.istio-system
  hosts:
    - {{ .Release.Name }}.entry.ctbiyi.com
  http:
    - route:
        - destination:
            host: {{ include "nginx.fullname" . }}

