apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server-ingress
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName=code-server-svc rewrite=/"
    nginx.org/websocket-services: "code-server-svc"
  namespace: demo
spec:
  ingressClassName: nginx
  rules:
    - host: k8s-ingress.gpg123.vip
      http:
        paths:
          - path: /code-server/
            pathType: Prefix
            backend:
              service:
                name: code-server-svc
                port:
                  number: 8080
#          - path: /ws
#            pathType: Prefix
#            backend:
#              service:
#                name: code-server-svc
#                port:
#                  number: 8080
