apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: config-volume
              mountPath: /data
              readOnly: false
      volumes:
        - name: config-volume
          configMap:
            defaultMode: 0777
            name: cm-test
            items:
              - key: demo.sh
                path: demo.sh
