apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress-route
  namespace: demo
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`whoami.zcrjjh.com`) && PathPrefix(`/notls`) # 指定域名
    kind: Rule
    services:
      - name: whoami
        kind: Service
        port: web
