apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
  namespace: demo
spec:
  #ingressClassName: traefik
  rules:
    - host: whoami.zcrjjh.com #spring-boot-demo-svc.demo.svc.cluster.local #
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
