apiVersion: v1
kind: Service
metadata:
  name: monitor-demo-svc
  namespace: demo
  labels:
    service: monitor-demo-svc
spec:
  selector:
    app: monitor-demo
  ports:
    - name: server
      protocol: TCP
      port: 80
      targetPort: 80
    - name: node-exporter
      protocol: TCP
      port: 9100
      targetPort: 9100
  type: NodePort

