apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-demo
  namespace: demo
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      port: node-exporter
    - interval: 15s
      path: /metrics
      port: cadvisor
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app: monitor-demo
      self-monitor: "true"
      release: kube-prometheus-stack

