apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: traefik-rule
  namespace: monitoring
spec:
  groups:
    - name: traefik.rules
      rules:
        - alert: TooManyRequest
          expr: avg(traefik_entrypoint_open_connections{job="traefik-dashboard",namespace="kube-system"}) > 5
          for: 1m
          labels:
            severity: critical
        - alert: HighCpuUsage
          expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 5m
          labels:
            severity: page
          annotations:
            summary: "High CPU usage detected on {{ $labels.instance }}"
            description: "{{ $labels.instance }} has had high CPU usage above 80% for the last 5 minutes."
