apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: traefik-rule
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus
spec:
  groups:
    - name: traefik-demo.rules
      rules:
        - alert: TooManyRequest
          expr: avg(traefik_entrypoint_open_connections{job="traefik-dashboard",namespace="kube-system"}) > 5
          for: 1m
          labels:
            severity: critical
          annotations:
            description: |
              节点 {{$labels.instance }}
              挂载目录 {{ $labels.mountpoint }}
              当前可用空间 {{ printf "%.2f" $value }}%
            summary: "111"
        - alert: HighCpuUsage
          expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 5m
          labels:
            severity: page
          annotations:
            summary: "High CPU usage detected on {{ $labels.instance }}"
            description: "{{ $labels.instance }} has had high CPU usage above 80% for the last 5 minutes."
