apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opentelemetry-operator-monitor
  namespace: opentelemetry
  labels:
    app.kubernetes.io/name: opentelemetry-operator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
spec:
  namespaceSelector:
    matchNames:
      - opentelemetry
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-operator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
