apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  labels:
    app: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      name: code-server
      labels:
        app: code-server
    spec:
      containers:
        - name: code-server
          image: codercom/code-server:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsGroup: 0
            runAsUser: 0
            privileged: true
          ports:
            - containerPort: 8080
              name: code-server
              protocol: TCP
          env:
            - name: USER
              value: root
            - name: PASSWORD
              value: root
          volumeMounts:
            - mountPath: /root/.config/code-server
              name: cm
            - mountPath: /home/coder
              name: host-code
            - mountPath: /root/.local/share/code-server
              name: host-config
      volumes:
        - name: cm
          configMap:
            name: code-server-cm
        - name: host-code
          hostPath:
            path: /home/ide/code-server/coder
        - name: host-config
          hostPath:
            path: /home/ide/code-server/configData
      restartPolicy: Always

