apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  labels:
    app.kubernetes.io/name: {{.Release.Name}}
    app.kubernetes.io/user: {{.Values.user}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Release.Name}}
      app.kubernetes.io/user: {{.Values.user}}
  template:
    metadata:
      name: {{.Release.Name}}
      labels:
        app.kubernetes.io/name: {{.Release.Name}}
        app.kubernetes.io/user: {{.Values.user}}
    spec:
      containers:
        - name: code-server
          image: codercom/code-server:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsGroup: 0
            runAsUser: 0
            privileged: true
          ports:
            - containerPort: 8080
              name: code-server
              protocol: TCP
          {{- if .Values.env }}
          env:
            {{ toYaml .Values.env | indent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /root/.config/code-server
              name: cm
            - mountPath: /home/coder/{{.Values.user}}
              name: host-code
            - mountPath: /root/.local/share/code-server
              name: host-config
              {{- range $name,$path := .Values.init }}
            - mountPath: {{$path}}
              name: {{$name}}
              {{- end }}
      volumes:
        - name: cm
          configMap:
            name: {{.Release.Name}}-cm
        - name: host-code
          hostPath:
            path: /home/ide/userData/{{.Values.user}}
        - name: host-config
          hostPath:
            path: /home/ide/config/configData
        {{- range $name,$path := .Values.init }}
        - hostPath: {{$path}}
          name: {{$name}}
          {{- end }}
      restartPolicy: Always

