apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}-ingress
  labels:
    app.kubernetes.io/name: {{.Release.Name}}
    app.kubernetes.io/user: {{.Values.user}}
spec:
  rules:
    - host: {{.Release.Name}}.ide.gpg123.vip
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Release.Name}}-svc
                port:
                  number: 8080

