apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-svc
  labels:
    app.kubernetes.io/name: {{.Release.Name}}
    app.kubernetes.io/user: {{.Values.user}}
spec:
  selector:
    app.kubernetes.io/name: {{.Release.Name}}
    app.kubernetes.io/user: {{.Values.user}}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

