#nginx-ingress多host合并控制器（必须安装）
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cafe-ingress-master
  annotations:
    nginx.org/mergeable-ingress-type: "master"
  namespace: demo
spec:
  ingressClassName: nginx
#  tls:
#    - hosts:
#        - lb.gpg123.vip
#      secretName: cafe-secret
  rules:
    - host: k8s-ingress.gpg123.vip
