apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Release.Name }}-cs-for-java
    userName: {{ .Values.userName }}
    releaseName: {{ .Release.Name }}
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      service: {{ .Release.Name }}-cs-for-java
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-cs-for-java
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: "Always"
      containers:
      - image: {{ .Values.codeServer.image }}
        imagePullPolicy: {{ .Values.codeServer.imagePullPolicy }}
        name: {{ .Release.Name }}-cs-for-java
        {{ if .Values.codeServer.git.urlAddress }}
        lifecycle:
          postStart:
            exec:
              command: [ "/bin/bash", "-c", "cd /home && ./git-ssh.sh {{.Values.userName}} {{.Values.codeServer.git.globalName}} {{.Values.codeServer.git.globalEmail}} {{.Values.codeServer.git.urlAddress}} >>/home/ide/{{.Values.userName}}/logfile.txt 2>&1" ]
        {{ end }}
        resources:
          requests:
            cpu: {{ .Values.codeServer.resources.requests.cpu }}
            memory: {{ .Values.codeServer.resources.requests.memory }}
          limits:
            cpu: {{ .Values.codeServer.resources.limits.cpu }}
            memory: {{ .Values.codeServer.resources.limits.memory }}
        ports:
        - containerPort: {{ .Values.codeServer.containerPort }}
        env:
        {{ if  .Values.codeServer.password}}
        - name: PASSWORD
          value: {{ .Values.codeServer.password }}
        {{ end }}
        {{ if .Values.codeServer.workSpacePath }}
        - name: workSpace
          value: /home/ide/{{ .Values.codeServer.workSpacePath }}
        {{ end }}
        {{ if  .Values.codeServer.git.urlAddress}}
        - name: gitUrl
          value: {{.Values.codeServer.git.urlAddress}}
        {{ end }}
        {{ if .Values.codeServer.git.globalName }}
        - name: gitGlobalName
          value: {{.Values.codeServer.git.globalName}}
        {{ end }}
        {{ if .Values.codeServer.git.globalEmail }}
        - name: gitGlobalEmail
          value: {{.Values.codeServer.git.globalEmail}}
        {{ end }}
        {{ if .Values.codeServer.resources.limits }}
        - name: resources
          value: {{.Values.codeServer.resources.limits.cpu}}c{{.Values.codeServer.resources.limits.memory}}g{{.Values.codeServer.resources.storage}}s
        {{ end }}
        - name: serviceName
          value: for-java
        - name: JAVA_HOME
          value: /usr/local/jdk8
        - name: MAVEN_HOME
          value: /usr/local/maven
        {{ if .Values.codeServer.key_path }}
        - name: key_path
          value: {{.Values.codeServer.key_path}}
        {{ end }}
        volumeMounts:
          - mountPath: /home/ide/{{ .Values.userName }}
            name: cs-for-java-data
            subPath: "{{ .Values.userName }}"
            readOnly: false
        securityContext:
          runAsUser: 0
      volumes:
        - name: cs-for-java-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc