apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-cs-for-java
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Release.Name }}.cloud.ide.com
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-cs-for-java-service
              servicePort: 80