apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-code-data
spec:
  capacity:
    storage: {{.Values.codeServer.resources.storage}}
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /data/nfside
    server: 192.168.176.20
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-token
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs
  nfs:
    path: /data/nfside
    server: 192.168.176.20
