apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-demo-monitor
  namespace: demo
  labels:
    app: spring-boot-demo
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8090"
spec:
  endpoints:
    - interval: 15s
      path: /actuator/prometheus
      port: http
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app: spring-boot-demo
