apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo-service
  namespace: demo
  labels:
    app: spring-boot-demo
    self-monitor: "true"
spec:
  selector:
    app: spring-boot-demo
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      name: http
  type: NodePort

