apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: spring-boot-demo-alert
  namespace: demo
spec:
  route:
    groupBy: [ 'job' ]
    groupWait: 10s
    groupInterval: 1m
    repeatInterval: 2h
    receiver: "webhook"
  receivers:
#    - name: 'email'
    - name: 'webhook'
      webhookConfigs:
        - url: 'https://webhook.site/c163ccbb-903b-4717-a156-d1895fa276a1'
        - url: 'https://webhook.site/c163ccbb-903b-4717-a156-d1895fa276a1'
      emailConfigs:
        - to: 'c163ccbb-903b-4717-a156-d1895fa276a1@emailhook.site'
        - to: '2694484453@qq.com'
